# ---- Loading libraries ----
library("shiny")
library("shinydashboard")
library("tidyverse")
library("leaflet")
library("plotly")
library("DT")
library("countrycode")

source("utils.R", local = T)

updateData <- function() {
  changed_date <<- readRDS("data/changed_date.RDS")
  current_date <<- readRDS("data/current_date.RDS")
  data_confirmed_10000th_case <<- readRDS("data/data_confirmed_10000th_case.RDS")
  data_10000th_death <<- readRDS("data/data_10000th_death.RDS")
  data_confirmed_1000th_case <<- readRDS("data/data_confirmed_1000th_case.RDS")
  data_1000th_death <<- readRDS("data/data_1000th_death.RDS")
  data_confirmed_100th_case <<- readRDS("data/data_confirmed_100th_case.RDS")
  data_100th_death <<- readRDS("data/data_100th_death.RDS")
  data_confirmed_10th_case <<- readRDS("data/data_confirmed_10th_case.RDS")
  data_10th_death <<- readRDS("data/data_10th_death.RDS")
  data_confirmed_1st_case <<- readRDS("data/data_confirmed_1st_case.RDS")
  data_1st_death <<- readRDS("data/data_1st_death.RDS")
  data_evolution <<- readRDS("data/data_evolution.RDS")
  data_latest <<- readRDS("data/data_latest.RDS")
  data_oecd <<- readRDS("data/data_oecd.RDS")
  data_oxford <<- readRDS("data/data_oxford.RDS")
  top5_countries <<- readRDS("data/top5_countries.RDS")
  data_world_bank <<- readRDS("data/data_world_bank.RDS")
  data_human_freedom <<- readRDS("data/data_human_freedom.RDS")
  data_full_table <<- readRDS("data/data_full_table.RDS")
  data_case_evolution <<- readRDS("data/data_case_evolution.RDS")
  data_trajectory_confirmed <<- readRDS("data/data_trajectory_confirmed.RDS")
  data_trajectory_deceased <<- readRDS("data/data_trajectory_deceased.RDS")
  data_greece_all <<- readRDS("data/data_greece_all.RDS")
  data_greece_cumulative <<- readRDS("data/data_greece_cumulative.RDS")
  data_greece_region <<- readRDS("data/data_greece_region.RDS")
  data_greece_region_timeline <<- readRDS("data/data_greece_region_timeline.RDS")
  data_greece_age_distribution <<- readRDS("data/data_greece_age_distribution.RDS")
  data_greece_age_averages <<- readRDS("data/data_greece_age_averages.RDS")
  data_greece_gender <<- readRDS("data/data_greece_gender.RDS")
}

updateData()