# ---- Loading libraries ----
library("shiny")
library("shinydashboard")
library("shinycssloaders")
library("tidyverse")
library("leaflet")
library("plotly")
library("DT")
library("countrycode")

source("utils.R", local = T)

updateData <- function() {
  changed_date <<- readRDS("data/changed_date.RDS")
  current_date <<- readRDS("data/current_date.RDS")
  data_confirmed_10000th_case <<- readRDS("data/data_confirmed_10000th_case.RDS")
  data_10000th_death <<- readRDS("data/data_10000th_death.RDS")
  data_confirmed_1000th_case <<- readRDS("data/data_confirmed_1000th_case.RDS")
  data_1000th_death <<- readRDS("data/data_1000th_death.RDS")
  data_confirmed_100th_case <<- readRDS("data/data_confirmed_100th_case.RDS")
  data_100th_death <<- readRDS("data/data_100th_death.RDS")
  data_confirmed_10th_case <<- readRDS("data/data_confirmed_10th_case.RDS")
  data_10th_death <<- readRDS("data/data_10th_death.RDS")
  data_confirmed_1st_case <<- readRDS("data/data_confirmed_1st_case.RDS")
  data_1st_death <<- readRDS("data/data_1st_death.RDS")
  data_evolution <<- readRDS("data/data_evolution.RDS")
  data_evolution_cases_after_100th <<- readRDS("data/data_evolution_cases_after_100th.RDS")
  data_evolution_deaths_after_10th <<- readRDS("data/data_evolution_deaths_after_10th.RDS")
  data_evolution_confirmed <<- readRDS("data/data_evolution_confirmed.RDS")
  data_evolution_confirmed_all <<- readRDS("data/data_evolution_confirmed_all.RDS")
  data_evolution_recovered <<- readRDS("data/data_evolution_recovered.RDS")
  data_evolution_recovered_all <<- readRDS("data/data_evolution_recovered_all.RDS")
  data_evolution_deceased <<- readRDS("data/data_evolution_deceased.RDS")
  data_evolution_deceased_all <<- readRDS("data/data_evolution_deceased_all.RDS")
  data_evolution_active <<- readRDS("data/data_evolution_active.RDS")
  data_evolution_active_all <<- readRDS("data/data_evolution_active_all.RDS")
  data_doubling_time_cases <<- readRDS("data/data_doubling_time_cases.RDS")
  data_doubling_time_deaths <<- readRDS("data/data_doubling_time_deaths.RDS")
  data_latest <<- readRDS("data/data_latest.RDS")
  data_oecd <<- readRDS("data/data_oecd.RDS")
  data_oxford <<- readRDS("data/data_oxford.RDS")
  top5_countries <<- readRDS("data/top5_countries.RDS")
  data_world_bank <<- readRDS("data/data_world_bank.RDS")
  data_human_freedom <<- readRDS("data/data_human_freedom.RDS")
  data_full_table <<- readRDS("data/data_full_table.RDS")
  data_case_evolution <<- readRDS("data/data_case_evolution.RDS")
  data_trajectory_confirmed <<- readRDS("data/data_trajectory_confirmed.RDS")
  data_trajectory_deceased <<- readRDS("data/data_trajectory_deceased.RDS")
}

updateData()
